<?php
/**
 * Maho
 *
 * @package    MageAustralia_CheckoutSuccess
 * @copyright  Copyright (c) 2026 Maho Australia
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @var MageAustralia_CheckoutSuccess_Block_Sales_Recurring_Profile_Schedule $this
 */
$profiles = $this->getRecurringProfiles();
if (empty($profiles)) {
    return;
}
?>
<div class="recurring-profile-summary">
    <h2 class="sub-title"><?php echo $this->__('Your recurring payment profiles:') ?></h2>
    <ul class="disc">
        <?php foreach ($profiles as $profile): ?>
            <?php
            $referenceId = $this->escapeHtml($this->getObjectData($profile, 'reference_id'));
            $profileIdHtml = $this->canViewProfiles()
                ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $referenceId)
                : $referenceId;
            ?>
            <li>
                <?php echo $this->__(
                    'Payment profile # %s: "%s".',
                    $profileIdHtml,
                    $this->escapeHtml($this->getObjectData($profile, 'schedule_description')),
                ) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
