<?php
/**
 * Maho
 *
 * @package    MageAustralia_CheckoutSuccess
 * @copyright  Copyright (c) 2026 Maho Australia
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @var MageAustralia_CheckoutSuccess_Block_Quick_Register $this
 */
?>
<div class="quick-account-create">
    <form action="<?php echo $this->escapeHtml($this->getRegisterPostUrl()) ?>" method="post" id="quick-register">
        <input type="hidden" name="form_key" value="<?php echo $this->escapeHtml($this->getFormKey()) ?>"/>
        <div class="fieldset">
            <h2><?php echo $this->__('Create account for next time') ?></h2>
            <p class="form-instructions">
                <?php echo $this->__(
                    'We\'ll register %s with this email so you can track this order and check out faster next time.',
                    '<strong>' . $this->escapeHtml($this->getCustomerEmail()) . '</strong>',
                ) ?>
            </p>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required">
                            <em>*</em> <?php echo $this->__('Password') ?>
                        </label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" autocomplete="new-password"
                                   minlength="8" required
                                   title="<?php echo $this->escapeHtml($this->__('Password')) ?>"
                                   class="input-text required-entry validate-password"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required">
                            <em>*</em> <?php echo $this->__('Confirm Password') ?>
                        </label>
                        <div class="input-box">
                            <input type="password" name="confirmation" id="confirmation" autocomplete="new-password"
                                   minlength="8" required
                                   title="<?php echo $this->escapeHtml($this->__('Confirm Password')) ?>"
                                   class="input-text required-entry validate-cpassword"/>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <button type="submit" class="button"
                    title="<?php echo $this->escapeHtml($this->__('Create Account')) ?>">
                <span><span><?php echo $this->__('Create Account') ?></span></span>
            </button>
        </div>
    </form>
</div>
