<?php
/**
 * Maho
 *
 * @package    MageAustralia_CheckoutSuccess
 * @copyright  Copyright (c) 2026 Maho Australia
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @var MageAustralia_CheckoutSuccess_Block_Additional $this
 */
?>
<div class="checkoutsuccess-additional">
    <?php foreach ($this->getRenderedBlocks() as $html): ?>
        <div class="checkoutsuccess-additional-block">
            <?php echo $html ?>
        </div>
    <?php endforeach; ?>
</div>
